import type { Metadata } from "next";
import { Inter } from "next/font/google";
const inter = Inter({ subsets: ["latin"] });

import "./globals.css";

import "@fontsource/roboto/300.css";
import "@fontsource/roboto/400.css";
import "@fontsource/roboto/500.css";
import "@fontsource/roboto/700.css";
import ThemeProviderClient from "./providers/ThemeProvider";
import { Box } from "@mui/material";
import Image from "next/image";

export const metadata: Metadata = {
  title: "Pet Connect",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <Box
          position="relative"
          width="100vw"
          py={14}
          display="grid"
          sx={{
            placeItems: "center",
          }}
        >
          <Image
            src="/background.png"
            alt="background"
            fill
            objectFit="cover"
            style={{
              zIndex: -1,
              position: "absolute",
              inset: 0,
            }}
          />
          <ThemeProviderClient>{children}</ThemeProviderClient>
        </Box>
      </body>
    </html>
  );
}
